from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Optional

class TransactionRequest(BaseModel):
    txn_id: str = Field(..., description="Unique transaction ID generated by gateway")
    payer_id: str = Field(..., description="UPI handle or account ID of the payer")
    payee_id: str = Field(..., description="UPI handle or account ID of the beneficiary")
    amount: float = Field(..., gt=0, description="Transaction amount in INR")
    location: str = Field(..., description="Geo location of the device")
    device_id: str = Field(..., description="Device signature or fingerprint")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="UTC transaction timestamp")

class EvaluationResponse(BaseModel):
    risk_score: int = Field(..., ge=0, le=100, description="Calculated transaction risk score")
    status: str = Field(..., description="LOW, MEDIUM, or HIGH risk classification")
    reasons: List[str] = Field(default_factory=list, description="Reason codes for the classification")
